apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "repave.fullname" . }}
  labels:
    {{- include "repave.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "repave.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "repave.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: payments-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
